import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FolderTree as TreeIcon } from "lucide-react";
import { auth } from "@/lib/auth";
import { cn } from "@/lib/util";
import { RepoHeader } from "@/component/header";
import Link from "next/link";
import { TreeViewProvider } from "@/context/view-filter";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  sidebar,
}: Readonly<{
  children: React.ReactNode;
  sidebar: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable
        )}
      >
        <TreeViewProvider>
          <div className="flex h-screen">
            <aside className="w-64 shadow-md">
              <div className="p-4">
                <Link href={"/"}>
                  <h1 className="text-xl font-bold flex items-center">
                    <TreeIcon className="mr-2" />
                    Repo Tree Viewer
                  </h1>
                </Link>
              </div>
              <div>{sidebar}</div>
            </aside>
            <main className="flex-1 overflow-x-hidden overflow-y-auto">
              <RepoHeader session={session} />
              {children}
            </main>
          </div>
        </TreeViewProvider>
      </body>
    </html>
  );
}
