import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FolderTree } from "lucide-react";
import { LoginButton, LogoutButton } from "@/component/auth-button";
import { auth } from "@/lib/auth";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  sidebar,
}: Readonly<{
  children: React.ReactNode;
  sidebar: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Header */}
        <div className="flex h-screen">
          {/* Sidebar */}
          <aside className="w-64 shadow-md">
            <div className="p-4">
              <h1 className="text-xl font-bold flex items-center">
                <FolderTree className="mr-2" />
                Repo Tree Viewer
              </h1>
            </div>
            {sidebar}
          </aside>
          {/* Main content */}
          <main className="flex-1 overflow-x-hidden overflow-y-auto">
            <header className="shadow-sm">
              <div className="max-w-7xl mx-auto py-4 px-4 sm:px-6 lg:px-8 flex justify-between items-center">
                <h2 className="text-lg font-semibold">Repository Tree</h2>
                {session ? (
                  <div className="flex items-center space-x-2">
                    <Image
                      src={session.user?.image ?? ""}
                      alt={session.user?.name ?? ""}
                      width={16}
                      height={16}
                      className="h-8 w-8 rounded-full"
                    />
                    <span>{session.user?.name}</span>
                    <LogoutButton />
                  </div>
                ) : (
                  <LoginButton />
                )}
              </div>
            </header>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
